# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-Firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseUI/Google'
pod 'Firebase/Firestore'
  # Pods for SwiftUI-Firebase

  target 'SwiftUI-FirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUI-FirebaseUITests' do
    # Pods for testing
  end

end
